project:
  type: book
  output-dir: docs

book:
  output-file: thesis
  title: "OverHAuL"
  subtitle: "Harnessing Automation for C Libraries with Large Language Models"
  date: 2025-07-27
  author:
    - name: "Konstantinos Chousos"
      email: "kchousos@di.uoa.gr"
      orcid: "0009-0008-6063-7915"
      url: "https://kchousos.github.io/"
      degrees:
        - BSc
      affiliations:
        - name: "National and Kapodistrian University of Athens"
          department: "Informatics and Telecommunications"
          city: "Athens"
          country: "Greece"
          url: "https://en.uoa.gr/"
          ror: "https://ror.org/04gnjpq42"
      roles: writing
      corresponding: true
  license: CC BY
  abstract: "Software vulnerabilities remain pervasive and challenging to detect, making robust testing approaches imperative. Fuzzing is an established software testing method for uncovering such vulnerabilities, through random input execution. Recent research has leveraged Large Language Models (LLMs) to enhance fuzz driver generation. However, most contemporary tools rely on additional resources beyond the target code, such as client programs or preexisting harnesses, limiting their scalability and applicability. In this thesis, we present OverHAuL, a neurosymbolic AI system that employs LLM agents to automatically generate fuzzing harnesses directly from library code, eliminating the need for auxiliary artifacts. To comprehensively evaluate OverHAuL, we construct a benchmark suite consisting of ten open-source C libraries. Our empirical analysis demonstrates that OverHAuL achieves an 81.25% success rate in harness generation across the evaluated projects, underscoring its effectiveness and potential to facilitate more efficient vulnerability discovery."

  chapters:
    - index.md
    - chapters/intro.md
    - chapters/background.md
    - chapters/overhaul.md 
    - chapters/evaluation.md
    - chapters/related.md
    - chapters/future.md
    - chapters/conclusion.md
    - chapters/refs.md # Bibliography
  appendices:
    - chapters/abandoned.md
    - chapters/sample-harnesses.md
    - chapters/prompts.md
  
  page-navigation: true
  page-footer: 
    center:
      - text: '&copy; 2025 Konstantinos Chousos'
    right:
      - text: "{{< iconify fa6-brands github >}}"
        url: "https://github.com/kchousos"
      - text: "{{< iconify academicons orcid >}}"
        url: "https://orcid.org/0009-0008-6063-7915"
      - text: "{{< iconify fa6-brands linkedin >}}"
        url: "https://www.linkedin.com/in/kchousos/"
      - text: "{{< iconify material-symbols mail >}}"
        url: "mailto:kchousos@di.uoa.gr"
  downloads: [pdf]
  repo-url: https://github.com/kchousos/BSc-Thesis/
  repo-branch: master
  # repo-actions: [edit, source]

bibliography: "./resources/bibliography.bib"
csl: "./resources/ieee-with-url.csl"

code-line-numbers: true

filters:
  - pseudocode

format:
  html:
    default: true
    html-math-method: katex
    reference-location: block
    citation: true
    toc: true
    toc-expand: true
    number-sections: true
    theme:
      light:
        - cosmo
        - ./resources/styles.scss
      dark:
        - cosmo
        - ./resources/styles.scss
        - ./resources/styles-dark.scss
    respect-user-color-scheme: true
    highlight-style: arrow
    date-format: long
    lightbox: true
    include-in-header:
      text: |
        <script src="https://tinylytics.app/embed/rSbhZ_sMtsVibUKrZtZ2/min.js" defer></script>
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
  pdf:
    default: true
    date: 2025-07-27
    date-format: MMMM, YYYY
    documentclass: scrreprt
    standalone: true
    number-sections: true
    keep-tex: true
    toc: false
    cite-method: biblatex
    mainfont: "Libertinus Serif"
    mainfontfallback:
      - "Liberation Serif:"
      - "NotoColorEmoji:mode=harf"
    sansfont: "Libertinus Sans"
    monofont: "Iosevka"
    mathfont: "Libertinus Math"
    numbersections: true
    biblio-style: ieee
    link-citations: true
    papersize: a4
    colorlinks: true
    boxlinks: false
    citecolor: red
    filecolor: cyan
    urlcolor: blue
    links-as-notes: false
    keywords: [LLMs, Fuzzing, Automation, Security, Neurosymbolic AI]
    highlight-style: a11y
    include-in-header: ./resources/preamble.tex
    fig-scap: true
    template-partials:
      - ./resources/before-body.tex

pdf-engine: lualatex
pdf-engine-opts:
  - '-shell-escape'

execute:
  freeze: true
