project:
  type: manuscript
  output-dir: docs

manuscript:
  article: thesis.qmd

bibliography: "./resources/bibliography.bib"
csl: "./resources/ieee-with-url.csl"

format:
  html:
    default: true
    theme: cosmo
    html-math-method: katex
    citation: true
  pdf:
    default: true
    documentclass: report
    standalone: true
    cite-method: biblatex
    mainfont: "Libertinus Serif"
    mainfontfallback:
      - "Liberation Serif:"
      - "NotoColorEmoji:mode=harf"
    sansfont: "Libertinus Sans"
    monofont: "Iosevka"
    mathfont: "Libertinus Math"
    numbersections: true
    biblio-style: ieee
    link-citations: true
    papersize: a4
    # urlstyle: tt
    geometry:
      - margin=1.4in
    # linestretch: 1.2
    colorlinks: true
    boxlinks: false
    citecolor: red
    filecolor: cyan
    urlcolor: blue
    links-as-notes: false
    filters:
      - ./resources/minted.lua
    header-includes: |
      \usepackage[newfloat, cache=false]{minted}
      \setminted{frame=single, framesep=2mm, linenos, breaklines, numbersep=0.5em}
      \makeatletter
      \let\listoflistings\relax
      \makeatother
      \usepackage[font={footnotesize}, margin=1cm, labelfont=bf]{caption}
      \captionsetup[listing]{position=top}

pdf-engine: lualatex
pdf-engine-opts:
  - '-shell-escape'

execute:
  freeze: true
