project:
  type: book
  output-dir: docs

book:
  output-file: thesis
  title: LLM-Driven Fuzzing
  subtitle: Automatic Harness Generation for Crypto Libraries
  description: This is, or rather will be, my BSc thesis.
  # date: 07-01-2025
  author:
    - name: Konstantinos Chousos
      email: sdi2000215@di.uoa.gr
      orcid: 0009-0008-6063-7915
      url: https://kchousos.github.io/
      degrees:
        - BSc
      affiliation:
        - name: National and Kapodistrian University of Athens
          department: Informatics and Telecommunications
          city: Athens
          country: Greece
          url: https://en.uoa.gr/
          ror: https://ror.org/04gnjpq42
      roles: writing
      corresponding: true
  license: CC BY
  abstract: Lorem ipsum odor amet, consectetuer adipiscing elit. Habitasse congue tempus erat rhoncus sapien interdum dolor nec. Posuere habitant metus tellus erat eu. Risus ultricies eu rhoncus, conubia euismod convallis commodo per. Nam tellus quisque maximus duis eleifend; arcu aptent. Nisi rutrum primis luctus tortor tempor maecenas. Donec curae cras dolor; malesuada ultricies scelerisque. Molestie class tincidunt quis gravida ut proin. Consequat lacinia arcu justo leo maecenas nunc neque ex. Platea eros ullamcorper nullam rutrum facilisis.

  chapters:
    - index.md
    - chapters/intro.md
    - chapters/refs.md
  
  page-navigation: true
  page-footer: 
    center:
      - text: '&copy; 2025 Konstantinos Chousos'
    right:
      - text: "{{< iconify fa6-brands github >}}"
        url: "https://github.com/kchousos"
      - text: "{{< iconify academicons orcid >}}"
        url: "https://orcid.org/0009-0008-6063-7915"
      - text: "{{< iconify fa6-brands linkedin >}}"
        url: "https://www.linkedin.com/in/kchousos/"
      - text: "{{< iconify material-symbols mail >}}"
        url: "mailto:sdi2000215@di.uoa.gr"
  downloads: [pdf]
  repo-url: https://github.com/kchousos/thesis/
  # repo-actions: [edit, source]
  repo-branch: master

bibliography: "./resources/bibliography.bib"
csl: "./resources/ieee-with-url.csl"

format:
  html:
    default: true
    html-math-method: katex
    citation: true
    toc: true
    toc-expand: true
    number-sections: true
    theme:
      light:
        - cosmo
        - ./resources/styles.scss
      dark:
        - cosmo
        - ./resources/styles.scss
        - ./resources/styles-dark.scss
    respect-user-color-scheme: true
    highlight-style: arrow
    date-format: long
    # filters: 
    #     - quarto
    #     - section-bibliographies
  pdf:
    default: true
    date: 07-01-2025
    date-format: MMMM, YYYY
    documentclass: scrreprt
    # classoption:
    #   - twoside
    #   - openright
    standalone: true
    number-sections: true
    keep-tex: true
    toc: false
    cite-method: biblatex
    mainfont: "Libertinus Serif"
    mainfontfallback:
      - "Liberation Serif:"
      - "NotoColorEmoji:mode=harf"
    sansfont: "Libertinus Sans"
    monofont: "Iosevka"
    mathfont: "Libertinus Math"
    numbersections: true
    biblio-style: ieee
    link-citations: true
    papersize: a4
    # urlstyle: tt
    # geometry:
    #   - margin=1.4in
    # linestretch: 1.2
    colorlinks: true
    boxlinks: false
    citecolor: red
    filecolor: cyan
    urlcolor: blue
    links-as-notes: false
    keywords: [LLMs, Fuzzing, Security, Neurosymbolic AI]
    filters:
      - ./resources/minted.lua
    include-in-header: ./resources/preamble.tex

pdf-engine: lualatex
pdf-engine-opts:
  - '-shell-escape'

execute:
  freeze: true
